ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver: "org.postgresql.Driver"
    username: "<DB_USERNAME>"
    password: "<DB_PASSWORD>"
    maximumPoolSize: 10
