ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module
  datasource:
    url: "jdbc:postgresql://:5432/postgres"
    driver: "org.postgresql.Driver"
    username: "postgres"
    password: ""
    maximumPoolSize: 10
